
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OpenDataApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BNFChapterDrugSpending
{

    public string Name { get; set; }

    public string DrugName { get; set; }

    public Nullable<decimal> TotalSpend { get; set; }

    public long Row { get; set; }

}

}
