//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugPracticeAndChapterSpend
    {
        public int Id { get; set; }
        public string PracNo { get; set; }
        public string BNFChapter { get; set; }
        public string DrugName { get; set; }
        public decimal TotalSpend { get; set; }
    }
}
