
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OpenDataApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GPPrescribing
{

    public int id { get; set; }

    public string PRACTICE { get; set; }

    public string Year { get; set; }

    public string Month { get; set; }

    public string VTM_NM { get; set; }

    public string VMP_NM { get; set; }

    public string AMP_NM { get; set; }

    public string Presentation { get; set; }

    public string Strength { get; set; }

    public string TotalItems { get; set; }

    public string TotalQuantity { get; set; }

    public string GrossCost { get; set; }

    public string ActualCost { get; set; }

    public string BNFCode { get; set; }

    public string BNFChapter { get; set; }

    public string BNFSection { get; set; }

    public string BNFParagraph { get; set; }

    public string BNFSubParagraph { get; set; }

}

}
