//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedsEntities : DbContext
    {
        public MedsEntities()
            : base("name=MedsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BNFCode> BNFCodes { get; set; }
        public virtual DbSet<GPPractice> GPPractices { get; set; }
        public virtual DbSet<GPPrescribing> GPPrescribings { get; set; }
        public virtual DbSet<MonthlyPrescriptionTotal> MonthlyPrescriptionTotals { get; set; }
        public virtual DbSet<PracticeTotalsPerMonth> PracticeTotalsPerMonths { get; set; }
        public virtual DbSet<DrugPracticeAndChapterSpend> DrugPracticeAndChapterSpends { get; set; }
        public virtual DbSet<BNFChapterDrugSpending> BNFChapterDrugSpendings { get; set; }
        public virtual DbSet<BNFChapterSpendSummary> BNFChapterSpendSummaries { get; set; }
        public virtual DbSet<ChapterSpending> ChapterSpendings { get; set; }
        public virtual DbSet<RegionPracticeDrugTotalSpend> RegionPracticeDrugTotalSpends { get; set; }
        public virtual DbSet<RegionSurgeryBNFSpendSummary> RegionSurgeryBNFSpendSummaries { get; set; }
    }
}
