//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPrescriptionTotal
    {
        public int @int { get; set; }
        public string Name { get; set; }
        public int Yr { get; set; }
        public string Mn { get; set; }
        public int TotalItems { get; set; }
    }
}
