
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OpenDataApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PracticeTotalsPerMonth
{

    public int Id { get; set; }

    public string PracNo { get; set; }

    public int Year { get; set; }

    public int Month { get; set; }

    public string BNFChapter { get; set; }

    public decimal TotalSpend { get; set; }

    public int TotalItems { get; set; }

}

}
