//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionPracticeDrugTotalSpend
    {
        public string PracNo { get; set; }
        public string PartnershipNo { get; set; }
        public string practiceName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Postcode { get; set; }
        public string TelNo { get; set; }
        public string LCG { get; set; }
        public string Name { get; set; }
        public string DrugName { get; set; }
        public decimal TotalSpend { get; set; }
    }
}
